name: Publish to PyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # 匹配如 v1.0.0 的正式版本标签
  workflow_dispatch:   # 允许手动触发

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史，用于版本标签
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine hatchling
    
    - name: Extract version from tag
      id: get_version
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        VERSION=${TAG_NAME#v}  # 移除前缀 'v'
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
    
    - name: Update version in pyproject.toml
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml
        echo "Updated version to: $VERSION"
        grep "^version" pyproject.toml
    
    - name: Build package
      run: |
        python -m build
        echo "Build completed successfully"
        ls -la dist/
    
    - name: Check package
      run: |
        python -m twine check dist/*
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.tag_name }}
        release_name: "Release ${{ steps.get_version.outputs.tag_name }}"
        body: |
          ## 正式版本发布 ${{ steps.get_version.outputs.tag_name }}
          
          已发布到 [PyPI](https://pypi.org/project/nonebot-plugin-dst-qq/)。
          
          ### 安装方式
          ```bash
          pip install nonebot-plugin-dst-qq==${{ steps.get_version.outputs.version }}
          ```
          
          ### 主要变更
          请查看提交历史了解详细变更内容。
          
          ### 升级说明
          如果从旧版本升级，请参考 README.md 中的升级指南。
        draft: false
        prerelease: false
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-files
        path: dist/